version: '3'
services:
  phpunit:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    entrypoint: ["vendor/phpunit/phpunit/phpunit"]
    command: ["./tests"]
    volumes:
      - .:/app
    working_dir: /app
  composer:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    entrypoint: ["/usr/bin/composer"]
    command: ["install", "-o"]
    volumes:
      - .:/app
    working_dir: /app